package com.fieldservice.entity;

public enum ActivityEventType {
    WORK_CREATED,
    WORK_STARTED,
    CHECKLIST_ITEM_COMPLETED,
    CHECKLIST_ITEM_REOPENED,
    ADDITIONAL_WORK_ADDED,
    ADDITIONAL_WORK_UPDATED,
    ADDITIONAL_WORK_DELETED,
    PHOTO_ADDED,
    PHOTO_DELETED,
    WORK_SUBMITTED,
    POC_APPROVED,
    POC_REJECTED,
    SUPERVISOR_APPROVED,
    SUPERVISOR_REJECTED,
    WORK_RESUMED,
    WORK_COMPLETED
}
